name: py_38
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - backcall=0.2.0
  - ca-certificates=2024.7.4
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.8.19
  - python_abi=3.8
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.34.2
      - adapters==1.0.0
      - aiohappyeyeballs==2.3.5
      - aiohttp==3.10.1
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.5.2
      - async-timeout==4.0.3
      - attrs==24.1.0
      - blessed==1.20.0
      - brotli==1.1.0
      - cachetools==5.4.0
      - certifi==2024.7.4
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - choreographer==1.0.9
      - cloudpickle==3.1.1
      - comet-ml==3.44.3
      - configobj==5.0.8
      - contourpy==1.1.1
      - cssselect2==0.7.0
      - cycler==0.12.1
      - datasets==3.1.0
      - dill==0.3.8
      - distro==1.9.0
      - dulwich==0.22.1
      - et-xmlfile==1.1.0
      - everett==3.1.0
      - exceptiongroup==1.3.0
      - filelock==3.15.4
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - google-auth==2.32.0
      - google-auth-oauthlib==1.0.0
      - gpustat==1.1.1
      - grpcio==1.65.4
      - h11==0.16.0
      - html5lib==1.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.24.5
      - idna==3.7
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - jiter==0.9.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kaleido==1.0.0
      - kiwisolver==1.4.5
      - lightning==2.3.3
      - lightning-utilities==0.11.6
      - llvmlite==0.41.1
      - logistro==1.1.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - narwhals==1.42.1
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - openai==1.99.3
      - openpyxl==3.1.5
      - orjson==3.10.15
      - pandas==2.0.3
      - peft==0.12.0
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - plotly==6.2.0
      - prettytable==3.10.2
      - protobuf==5.27.3
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydyf==0.10.0
      - pyparsing==3.1.2
      - pyphen==0.16.0
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - pytorch-ignite==0.5.0.post2
      - pytorch-lightning==2.4.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - regex==2024.7.24
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==13.7.1
      - rpds-py==0.19.1
      - rsa==4.9
      - rtdl-revisiting-models==0.0.2
      - safetensors==0.4.4
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.12.0
      - shap==0.44.1
      - simplejson==3.20.1
      - slicer==0.0.7
      - sniffio==1.3.1
      - sympy==1.13.1
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - torch==2.4.0
      - torchaudio==2.4.0
      - torchmetrics==1.4.1
      - torchvision==0.19.0
      - tqdm==4.66.5
      - transformers==4.43.4
      - triton==3.0.0
      - tzdata==2024.1
      - urllib3==2.2.2
      - weasyprint==61.2
      - webencodings==0.5.1
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - wurlitzer==3.1.1
      - xxhash==3.5.0
      - yarl==1.9.4
      - zipp==3.19.2
      - zopfli==0.2.3.post1

